name: Check build size
on:
  push:
    branches: [master, main]
jobs:
  build-and-codechecks:
    name: build and run codechecks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: yarn install and build
        run: |
          corepack enable
          yarn set version stable
          yarn install
          yarn build
          npx codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
